import { existsSync } from "node:fs";
import { lstat, mkdir, readFile, rm, rmdir, symlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import * as p from "@clack/prompts";
import pc from "picocolors";
import { readManifest, writeManifest } from "../manifest.js";
import {
  collectMcpConfig,
  getAdapter,
  listAdapters,
} from "../adapters.js";

async function requireManifest(projectRoot) {
  const manifest = await readManifest(projectRoot);
  if (!manifest) {
    p.log.error(
      'Praxis is not initialized in this project. Run "praxis init" first.'
    );
    process.exit(1);
  }
  return manifest;
}

/**
 * Writes the output entries from an adapter transform to disk.
 * Returns the number of files written.
 */
async function writeAdapterFiles(projectRoot, entries) {
  let written = 0;

  for (const entry of entries) {
    const fullPath = resolve(projectRoot, entry.path);

    if (entry.type === "symlink") {
      // Handle symlink (CLAUDE.md → AGENTS.md)
      // Use lstat (not existsSync) to detect dangling symlinks too
      try {
        const stats = await lstat(fullPath);
        if (stats.isSymbolicLink()) {
          // Already a symlink — overwrite it
          await rm(fullPath);
        } else {
          // Regular file exists — warn and skip
          p.log.warn(
            `${entry.path} already exists and is not a symlink — skipping. Remove it manually if you want Praxis to manage it.`
          );
          continue;
        }
      } catch {
        // Path does not exist — proceed to create
      }

      await symlink(entry.target, fullPath);
      written++;
      p.log.success(`${pc.green("created")} ${entry.path} → ${entry.target}`);
    } else {
      // Handle regular file
      await mkdir(dirname(fullPath), { recursive: true });

      if (entry.mergeKey && existsSync(fullPath)) {
        // Merge into existing file (e.g., opencode.json)
        try {
          const existing = JSON.parse(await readFile(fullPath, "utf-8"));
          const newContent = JSON.parse(entry.content);
          existing[entry.mergeKey] = newContent[entry.mergeKey];
          await writeFile(
            fullPath,
            JSON.stringify(existing, null, 2) + "\n"
          );
        } catch {
          // If existing file is invalid JSON, overwrite it
          await writeFile(fullPath, entry.content);
        }
      } else {
        await writeFile(fullPath, entry.content);
      }

      written++;
      p.log.success(`${pc.green("written")} ${entry.path}`);
    }
  }

  return written;
}

/**
 * Removes the files generated by an adapter. Returns the number of files removed.
 */
async function removeAdapterFiles(projectRoot, adapterName, mcpConfig) {
  const adapter = getAdapter(adapterName);
  const entries = adapter.transform(mcpConfig);
  let removed = 0;

  const removedDirs = new Set();

  for (const entry of entries) {
    const fullPath = resolve(projectRoot, entry.path);

    if (!existsSync(fullPath)) continue;

    if (entry.mergeKey) {
      // For merge-key files (opencode.json), only remove the managed key
      try {
        const existing = JSON.parse(await readFile(fullPath, "utf-8"));
        delete existing[entry.mergeKey];

        if (Object.keys(existing).length === 0) {
          await rm(fullPath);
        } else {
          await writeFile(
            fullPath,
            JSON.stringify(existing, null, 2) + "\n"
          );
        }
      } catch {
        await rm(fullPath);
      }
    } else {
      await rm(fullPath);
    }

    removed++;
    p.log.success(`${pc.red("removed")} ${entry.path}`);

    const dir = dirname(fullPath);
    const resolvedRoot = resolve(projectRoot);
    if (dir.length > resolvedRoot.length) {
      removedDirs.add(dir);
    }
  }

  // Clean up empty parent directories
  for (const dir of removedDirs) {
    try {
      await rmdir(dir);
    } catch {
      // Not empty or already gone
    }
  }

  return removed;
}

export async function toolAdd(names) {
  const projectRoot = process.cwd();

  p.intro(pc.bold("Praxis — Tool Add"));

  const manifest = await requireManifest(projectRoot);
  const allAdapters = listAdapters();
  const enabledTools = new Set(manifest.enabledTools);

  let selectedNames;

  if (names.length === 0) {
    // Interactive multi-select
    const options = allAdapters.map((a) => ({
      value: a.name,
      label: `${a.displayName} (${a.files.join(", ")})`,
    }));

    const selected = await p.multiselect({
      message: "Select tools to configure:",
      options,
      initialValues: [...enabledTools],
      required: false,
    });

    if (p.isCancel(selected)) {
      p.cancel("Cancelled.");
      process.exit(0);
    }

    selectedNames = selected;
  } else {
    // Validate provided names
    const validNames = new Set(allAdapters.map((a) => a.name));
    for (const name of names) {
      if (!validNames.has(name)) {
        p.log.error(
          `Unknown tool "${name}". Available: ${[...validNames].join(", ")}`
        );
        process.exit(1);
      }
    }
    selectedNames = names;
  }

  if (selectedNames.length === 0) {
    p.outro("No tools selected.");
    return;
  }

  const mcpConfig = await collectMcpConfig(projectRoot, manifest);
  let totalWritten = 0;

  for (const name of selectedNames) {
    const adapter = getAdapter(name);
    const entries = adapter.transform(mcpConfig);
    const written = await writeAdapterFiles(projectRoot, entries);
    totalWritten += written;
    enabledTools.add(name);
  }

  await writeManifest(projectRoot, {
    ...manifest,
    updatedAt: new Date().toISOString(),
    enabledTools: [...enabledTools],
  });

  p.outro(
    `Done! ${pc.green(totalWritten)} file(s) written for ${selectedNames.join(", ")}.`
  );
}

export async function toolRemove(names) {
  const projectRoot = process.cwd();

  p.intro(pc.bold("Praxis — Tool Remove"));

  const manifest = await requireManifest(projectRoot);
  const enabledTools = new Set(manifest.enabledTools);

  if (names.length === 0) {
    p.log.error("Please specify one or more tool names to remove.");
    process.exit(1);
  }

  const validNames = new Set(listAdapters().map((a) => a.name));
  for (const name of names) {
    if (!validNames.has(name)) {
      p.log.error(
        `Unknown tool "${name}". Available: ${[...validNames].join(", ")}`
      );
      process.exit(1);
    }
  }

  const mcpConfig = await collectMcpConfig(projectRoot, manifest);
  let totalRemoved = 0;

  for (const name of names) {
    const removed = await removeAdapterFiles(projectRoot, name, mcpConfig);
    totalRemoved += removed;
    enabledTools.delete(name);
  }

  await writeManifest(projectRoot, {
    ...manifest,
    updatedAt: new Date().toISOString(),
    enabledTools: [...enabledTools],
  });

  p.outro(
    `Done! ${pc.red(totalRemoved)} file(s) removed for ${names.join(", ")}.`
  );
}

export async function toolList() {
  const projectRoot = process.cwd();

  p.intro(pc.bold("Praxis — Tool List"));

  const manifest = await requireManifest(projectRoot);
  const enabledTools = new Set(manifest.enabledTools);
  const allAdapters = listAdapters();

  for (const adapter of allAdapters) {
    const status = enabledTools.has(adapter.name)
      ? pc.green("enabled")
      : pc.dim("disabled");
    const files = adapter.files.map((f) => pc.dim(f)).join(", ");
    p.log.message(`${adapter.displayName} (${adapter.name}) — ${status}\n  Files: ${files}`);
  }

  p.outro(`${allAdapters.length} tool adapter(s) available.`);
}
